name: canvas_text_editor
description: An canvas text editor web app like Google Docs port from ts.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  web: ^1.1.1
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
  path: any

dependency_overrides:
#quebra-compatibilidade entre o analyzer 7.x e o mockito 5.4.5 
#(o gerador de mocks do mockito usa tipos internos do analyzer 
#como InterfaceElementImpl; a partir do analyzer 7.4.0 isso quebrou).
  #analyzer: 7.3.0
  
